### ISSUE TITLE
MSBuild team is changing "{major}.0" to "Current"

### ISSUE THREAD

**Issue by 3F** [3F/hMSBuild#10]
> MSBuild team is changing "{major}.0" to "Current" to make VS2019 and newer easier to automate in devops via vswhere.

https://github.com/Microsoft/vswhere/issues/162#issuecomment-452933011

**Comment by gerhardol** [comment]
Any thoughts about the permanent solution?
The following works so far, but from the vswhere discussion, a better should be done

![image](https://user-images.githubusercontent.com/6248932/56532526-360e2400-6556-11e9-9afd-46f28f142618.png)

**Comment by 3F** [comment]
@gerhardol Here's src for this part, you can use PR: https://github.com/3F/hMSBuild/blob/master/frontend.bat#L522

About solution, what about future **17+** VS releases ? :) 

I think `GEQ` operator is enough.

Also, I don't know more details about an "Current" naming, but just to be sure ( https://github.com/3F/hMSBuild/issues/3#issuecomment-322837934 ) probably we also need to check this dir like ~

```bat
if !vsver! GEQ 16 if exist "!thisDir!" (
	...
)
```
or maybe not ... well you can open PR, I will look into later. 


Please also test the new solution in real usage. Thanks!
*use build.bat for manual compile for your PC, or see CI appveyor*
