### ISSUE TITLE
Non-zero exit code when compilation fails

### ISSUE THREAD

**Issue by uli-weltersbach** [3F/hMSBuild#4]
I love your script, but I always end up modifying line 231 (v1.2.1) to return %ERRORLEVEL% instead of zero, so that hMSBuild.bat returns a non-zero exit code when MSBuild.exe fails.

Is there any reason why you decided to always return zero, even when MSBuild.exe encounters an error?

**Comment by 3F** [comment]
Seems I left it from the initial draft. Yes the !ERRORLEVEL! is better option after call !xMSBuild! :)

I'll update this later, but you can also use pull-request, raw frontend is here:
https://github.com/3F/hMSBuild/blob/master/frontend.bat

*btw, I've also plan to update GetNuTool core on this week if you're using it*
